# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
 
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
 
name: Cloudformation template
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
 
    - uses: actions/upload-artifact@v4
      with:
        name: my-new-case-study-1.0-SNAPSHOT-lambda-package
        path: ./target
 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 
    - name: Upload artifact zip to S3 bucket
      run: aws s3 cp ./target/my-new-case-study-1.0-SNAPSHOT-lambda-package.zip s3://aws-weather-app-bucket/
    - name: Upload cloudformation template to S3 bucket
      run: aws s3 cp ./template.yaml s3://aws-weather-app-bucket/
 
  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: build
 
    steps: 
    - uses: actions/download-artifact@v4
      with:
        name: my-new-case-study-1.0-SNAPSHOT-lambda-package
        path: ./target
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: new-aws-weather-app-stack
        template: https://aws-weather-app-bucket.s3.amazonaws.com/template.yaml
        no-fail-on-empty-changeset: "1"
